name: thera
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.6.1=py36_0
  - astor=0.7.1=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=1.5.0=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py36_0
  - cudatoolkit=8.0=3
  - cudnn=7.1.3=cuda8.0_0
  - cycler=0.10.0=py36_0
  - cython=0.29=py36he6710b0_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py36_0
  - entrypoints=0.2.3=py36_2
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.0=py36_0
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - grpcio=1.12.1=py36hdbcaa40_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py36h989c5e5_3
  - hdf5=1.10.2=hba1933b_1
  - html5lib=0.9999999=py36_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.0=118
  - ipykernel=5.1.0=py36h39e3cac_0
  - ipython=7.1.1=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.4.2=py36_0
  - jedi=0.13.1=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=6.0.0=py36_0
  - jupyter_core=4.4.0=py36_0
  - keras=2.2.4=0
  - keras-applications=1.0.6=py36_0
  - keras-base=2.2.4=py36_0
  - keras-preprocessing=1.0.5=py36_0
  - kiwisolver=1.0.1=py36hf484d3e_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.35=hbc83047_0
  - libprotobuf=3.6.1=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - markdown=3.0.1=py36_0
  - markupsafe=1.0=py36h14c3975_1
  - matplotlib=3.0.1=py36h5429711_0
  - mistune=0.8.4=py36h7b6447c_0
  - nbconvert=5.3.1=py36_0
  - nbformat=4.4.0=py36_0
  - ncurses=6.1=hf484d3e_0
  - notebook=5.7.0=py36_0
  - numpy=1.15.3=py36h1d66e8a_0
  - numpy-base=1.15.3=py36h81de0dd_0
  - olefile=0.46=py36_0
  - openssl=1.0.2p=h14c3975_0
  - pandas=0.23.4=py36h04863e7_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.3.1=py36_0
  - patsy=0.5.1=py36_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=5.3.0=py36h34e0f95_0
  - pip=10.0.1=py36_0
  - prometheus_client=0.4.2=py36_0
  - prompt_toolkit=2.0.7=py36_0
  - protobuf=3.6.1=py36he6710b0_0
  - ptyprocess=0.6.0=py36_0
  - pygments=2.2.0=py36_0
  - pyparsing=2.2.2=py36_0
  - pyqt=5.9.2=py36h05f1152_2
  - python=3.6.6=h6e4f718_2
  - python-dateutil=2.7.5=py36_0
  - pytz=2018.7=py36_0
  - pyyaml=3.13=py36h14c3975_0
  - pyzmq=17.1.2=py36h14c3975_0
  - qt=5.9.6=h8703b6f_2
  - qtconsole=4.4.2=py36_0
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.20.0=py36h4989274_1
  - seaborn=0.9.0=py36_0
  - send2trash=1.5.0=py36_0
  - setuptools=39.1.0=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.11.0=py36_1
  - sqlite=3.25.2=h7b6447c_0
  - statsmodels=0.9.0=py36h035aef0_0
  - tensorboard=1.11.0=py36hf484d3e_0
  - tensorflow=1.11.0=mkl_py36ha6f0bda_0
  - tensorflow-base=1.11.0=mkl_py36h3c3e929_0
  - tensorflow-gpu=1.4.1=0
  - tensorflow-gpu-base=1.4.1=py36h01caf0a_0
  - tensorflow-tensorboard=1.5.1=py36hf484d3e_1
  - termcolor=1.1.0=py36_1
  - terminado=0.8.1=py36_1
  - testpath=0.4.2=py36_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py36h7b6447c_0
  - traitlets=4.3.2=py36_0
  - wcwidth=0.1.7=py36_0
  - werkzeug=0.14.1=py36_0
  - wheel=0.32.2=py36_0
  - widgetsnbextension=3.4.2=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.2.5=hf484d3e_1
  - zlib=1.2.11=ha838bed_2
  - pip:
    - pydicom==1.2.0
    - simpleitk==1.1.0
prefix: /home/valentin/anaconda3/envs/thera

